[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "long_test: marks tests as slow (deselect with '--long_test')"
]
minversion = "6.0"
addopts = "-ra"
testpaths = "tests"
