# MIT License
#
# Copyright (c) 2022 Quandela
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# As a special exception, the copyright holders of exqalibur library give you
# permission to combine exqalibur with code included in the standard release of
# Perceval under the MIT license (or modified versions of such code). You may
# copy and distribute such a combined system following the terms of the MIT
# license for both exqalibur and Perceval. This exception for the usage of
# exqalibur is limited to the python bindings used by Perceval.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from copy import copy
from typing import Any

from perceval.utils.constants import KEY_EXPERIMENT, KEY_CIRCUIT, KEY_RESULT_MAPPING, KEY_MAPPING_PARAMETERS, \
    KEY_JOB_CONTEXT, KEY_COMPUTATION, KEY_MAX_SAMPLES, KEY_MAX_SHOTS, KEY_COMMAND, KEY_NOISE, KEY_PARAMETERS, \
    KEY_INPUT_STATE, KEY_POSTSELECT, KEY_HERALDS, KEY_MIN_DETECTED_PHOTONS, KEY_ITERATOR
from perceval.components import Experiment

from .abstract_computer import AbstractComputer
from .computation import Computation
from .computation_iterator import ComputationIterator
from .payload_generator import PayloadGenerator


class PayloadUpdater:

    @staticmethod
    def update_payload(payload: dict[str, Any], computer: AbstractComputer):
        """
        :param payload: A payload, generated by a perceval version above 0.10
        :param computer: The computer on which the payload will be executed.
        :return: A new dictionary with the payload, up-to-date with the current perceval version.
        """
        payload = PayloadUpdater.update_to_1_0(payload)
        return PayloadUpdater.update_to_1_3(payload, computer)

    @staticmethod
    def update_to_1_0(payload: dict[str, Any]) -> dict[str, Any]:
        """
        :param payload: A payload, generated by a perceval version above 0.10
        :return: A new dictionary with the payload, up-to-date with perceval version 1.0 format.
        """
        to_experiment = PayloadUpdater._must_change_to_experiment(payload)
        if to_experiment:
            return PayloadUpdater._update_experiment(payload)
        return payload

    @staticmethod
    def _update_experiment(payload: dict[str, Any]) -> dict[str, Any]:
        # For each key defined in Experiment, sets it in a new experiment and deletes the keys from data
        res = copy(payload)
        experiment = Experiment()
        if KEY_CIRCUIT in res:
            experiment.set_circuit(res.pop(KEY_CIRCUIT))

        if experiment.m is not None and KEY_INPUT_STATE in res:  # We can only add input state if a circuit is defined
            experiment.with_input(res.pop(KEY_INPUT_STATE))

        if KEY_NOISE in res:
            experiment.noise = res.pop(KEY_NOISE)

        if KEY_POSTSELECT in res:
            experiment.set_postselection(res.pop(KEY_POSTSELECT))

        if KEY_HERALDS in res:
            heralds = res.pop(KEY_HERALDS)
            for m, v in heralds.items():
                experiment.add_herald(int(m), v)

        # Note: the other ports were not serialized, nor do the detectors

        if KEY_PARAMETERS in res:
            params = copy(res[KEY_PARAMETERS])

            if KEY_MIN_DETECTED_PHOTONS in params:
                experiment.min_detected_photons_filter(params.pop(KEY_MIN_DETECTED_PHOTONS))

            res[KEY_PARAMETERS] = params

        res[KEY_EXPERIMENT] = experiment
        return res

    @staticmethod
    def _must_change_to_experiment(data: dict[str, Any]) -> bool:
            if KEY_CIRCUIT in data:  # All old payloads would have these if it now requires an experiment
                return True
            return False

    @staticmethod
    def update_to_1_3(payload: dict[str, Any], computer: AbstractComputer) -> dict[str, Any]:
        """
        :param payload: A payload, generated by a perceval version above 1.0
        :param computer: The computer on which the payload will be executed.
        :return: A new dictionary with the payload, up-to-date with perceval version 1.3 format.
        """
        if KEY_COMPUTATION in payload:
            return payload

        payload = copy(payload)
        samples = None
        shots = None

        if (context := payload.pop(KEY_JOB_CONTEXT, None)) is not None:
            command_str = context[KEY_RESULT_MAPPING][1].split("_to_")[1]
            if KEY_MAPPING_PARAMETERS in context:
                samples = context[KEY_MAPPING_PARAMETERS].get(KEY_MAX_SAMPLES)
                shots = context[KEY_MAPPING_PARAMETERS].get(KEY_MAX_SHOTS)

        else:
            command_str = payload.pop(KEY_COMMAND)
            samples = payload.pop(KEY_MAX_SAMPLES)
            shots = payload.pop(KEY_MAX_SHOTS)

        command = computer.get_command(command_str)
        computation = Computation(command, payload.pop(KEY_EXPERIMENT, Experiment()))

        if samples is not None:
            computation.add_params(max_samples = samples)
        if shots is not None:
            computation.add_params(max_shots = shots)

        base_computation = computation

        if KEY_ITERATOR in payload:
            iterator = payload.pop(KEY_ITERATOR)

            computation = ComputationIterator(computation)
            for iteration in iterator:
                if KEY_NOISE in iteration:
                    del iteration[KEY_NOISE]  # No longer supported - Just ignore it  # TODO: logging.warning ?

                computation.add_iteration(**iteration)

        noise = computation.experiment.noise  # Use legacy way to fill in the noise
        parameters = payload.pop(KEY_PARAMETERS, None)

        for key, value in payload.items():
            try:
                base_computation.add_params(**{key: value})
            except TypeError:
                pass  # Logging ?

        return PayloadGenerator.from_computation(computation, noise=noise, parameters=parameters)
