# MIT License
#
# Copyright (c) 2022 Quandela
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# As a special exception, the copyright holders of exqalibur library give you
# permission to combine exqalibur with code included in the standard release of
# Perceval under the MIT license (or modified versions of such code). You may
# copy and distribute such a combined system following the terms of the MIT
# license for both exqalibur and Perceval. This exception for the usage of
# exqalibur is limited to the python bindings used by Perceval.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from copy import copy, deepcopy
from typing import Any

from perceval.utils.constants import KEY_EXPERIMENT, KEY_CIRCUIT, KEY_RESULT_MAPPING, KEY_MAPPING_PARAMETERS, \
    KEY_JOB_CONTEXT, KEY_COMPUTATION, KEY_MAX_SAMPLES, KEY_MAX_SHOTS, KEY_COMMAND, KEY_NOISE, KEY_PARAMETERS, \
    KEY_INPUT_STATE, KEY_POSTSELECT, KEY_HERALDS, KEY_MIN_DETECTED_PHOTONS, KEY_ITERATOR
from perceval.components import Experiment

from .abstract_computer import AbstractComputer
from .computation import Computation
from .computation_iterator import ComputationIterator
from .payload_generator import PayloadGenerator


class PayloadUpdater:
    max_version: int = 2

    @staticmethod
    def update_payload(payload: dict[str, Any], computer: AbstractComputer | None, target_payload_version: int = None) -> dict[str, Any]:
        """
        :param payload: A payload, generated by a perceval version above 0.10
        :param computer: The computer on which the payload will be executed. Can be None if target_payload_version is 0 or 1
        :param target_payload_version: The version of the wanted result payload.
            Version 0 corresponds to perceval from 0.10 up to 0.12
            Version 1 corresponds to perceval from 0.13 up to 1.2
            Version 2 corresponds to perceval from 1.3 up to now. Default value.
        :return: A new dictionary with the payload, up-to-date with the current perceval version.
        """
        version = PayloadUpdater._estimate_version(payload)

        if target_payload_version is None:
            target_payload_version = PayloadUpdater.max_version

        if target_payload_version < 0 or target_payload_version > PayloadUpdater.max_version:
            raise ValueError(f"Unknown target version (received {target_payload_version}, expected it between 0 and {PayloadUpdater.max_version})")

        if version < target_payload_version:
            if version < 1 <= target_payload_version:
                payload = PayloadUpdater._update_to_v1(payload)
                version = 1
            if version < 2 <= target_payload_version:
                if computer is None:
                    raise RuntimeError("Can't update a payload to version 2 if no Computer is given")
                payload = PayloadUpdater._update_to_v2(payload, computer)

        elif version > target_payload_version:
            if target_payload_version == 0:
                raise NotImplementedError("Downgrade to payload version 0 is not implemented")

            if version > 1 >= target_payload_version:
                if computer is None:
                    raise RuntimeError("Can't downgrade a payload to version 1 if no Computer/RemoteProcessor is given")
                payload = PayloadUpdater._downgrade_to_v1(payload, computer.available_commands)

        return payload

    @staticmethod
    def _estimate_version(payload: dict) -> int:
        if KEY_COMPUTATION in payload:
            return 2
        if KEY_EXPERIMENT in payload:
            return 1
        return 0

    @staticmethod
    def _update_to_v1(payload: dict[str, Any]) -> dict[str, Any]:
        """
        For each key defined in Experiment, sets it in a new experiment and deletes the keys.

        :param payload: A payload, generated by a perceval version above 0.10
        :return: A new dictionary with the payload, up-to-date with perceval version 1.0 format.
        """
        if KEY_CIRCUIT not in payload:
            return payload

        res = copy(payload)
        experiment = Experiment()
        if KEY_CIRCUIT in res:
            experiment.set_circuit(res.pop(KEY_CIRCUIT))

        if experiment.m is not None and KEY_INPUT_STATE in res:  # We can only add input state if a circuit is defined
            experiment.with_input(res.pop(KEY_INPUT_STATE))

        if KEY_NOISE in res:
            experiment.noise = res.pop(KEY_NOISE)

        if KEY_POSTSELECT in res:
            experiment.set_postselection(res.pop(KEY_POSTSELECT))

        if KEY_HERALDS in res:
            heralds = res.pop(KEY_HERALDS)
            for m, v in heralds.items():
                experiment.add_herald(int(m), v)

        # Note: the other ports were not serialized, nor do the detectors

        if KEY_PARAMETERS in res:
            params = copy(res[KEY_PARAMETERS])

            if KEY_MIN_DETECTED_PHOTONS in params:
                experiment.min_detected_photons_filter(params.pop(KEY_MIN_DETECTED_PHOTONS))

            res[KEY_PARAMETERS] = params

        res[KEY_EXPERIMENT] = experiment
        return res

    _METHOD_MAPPING = {
        'probs':        {'sample_count': "sample_count_to_probs", 'samples': "samples_to_probs"},
        'sample_count': {'probs': "probs_to_sample_count",        'samples': "samples_to_sample_count"},
        'samples':      {'probs': "probs_to_samples",             'sample_count': "sample_count_to_samples"}
    }

    @staticmethod
    def _get_primitive_converter(method: str, available_commands: list[str]) -> tuple[str, str | None]:
        if method in available_commands:
            return method, None
        if method in PayloadUpdater._METHOD_MAPPING:
            pmap = PayloadUpdater._METHOD_MAPPING[method]
            for k, converter in pmap.items():
                if k in available_commands:
                    return k, converter
        return method, None

    @staticmethod
    def _downgrade_to_v1(payload: dict[str, Any], available_commands: list[str]) -> dict[str, Any]:
        if KEY_COMPUTATION not in payload:
            return payload

        payload = deepcopy(payload)
        computation: Computation | ComputationIterator = payload.pop(KEY_COMPUTATION)

        if KEY_NOISE in payload:
            computation.experiment.noise = payload.pop(KEY_NOISE)
        payload[KEY_EXPERIMENT] = computation.experiment
        if isinstance(computation, ComputationIterator):
            payload[KEY_ITERATOR] = computation.iterations

        payload |= computation.parameters

        command_name = computation.command.name
        primitive, converter = PayloadUpdater._get_primitive_converter(command_name, available_commands)
        if converter is None:
            job_context = None
        else:
            method_is_probs = (command_name.find('sample') == -1)
            primitive_is_probs = (primitive.find('sample') == -1)
            job_context = {"result_mapping": ['perceval.utils', converter]}

            if not method_is_probs and primitive_is_probs:
                job_context["mapping_delta_parameters"] = {}
                if KEY_MAX_SAMPLES in payload:
                    job_context["mapping_delta_parameters"][KEY_MAX_SAMPLES] = payload.pop(KEY_MAX_SAMPLES)
                if KEY_MAX_SHOTS:
                    # The pop here reproduces the Sampler's behavior, but this is strange as Quandela cloud expects the max_shots to have a value
                    # Anyway, this case never appears as it only appears if the platform can only do probs, which corresponds to no platform
                    job_context["mapping_delta_parameters"][KEY_MAX_SHOTS] = payload.pop(KEY_MAX_SHOTS)

        payload[KEY_COMMAND] = primitive
        payload[KEY_JOB_CONTEXT] = job_context

        return payload

    @staticmethod
    def _update_to_v2(payload: dict[str, Any], computer: AbstractComputer) -> dict[str, Any]:
        """
        :param payload: A payload, generated by a perceval version above 1.0
        :param computer: The computer on which the payload will be executed.
        :return: A new dictionary with the payload, up-to-date with perceval version 1.3 format.
        """
        if KEY_COMPUTATION in payload:
            return payload

        payload = copy(payload)
        samples = None
        shots = None

        if (context := payload.pop(KEY_JOB_CONTEXT, None)) is not None:
            command_str = context[KEY_RESULT_MAPPING][1].split("_to_")[1]
            if KEY_MAPPING_PARAMETERS in context:
                samples = context[KEY_MAPPING_PARAMETERS].get(KEY_MAX_SAMPLES)
                shots = context[KEY_MAPPING_PARAMETERS].get(KEY_MAX_SHOTS)

        else:
            command_str = payload.pop(KEY_COMMAND)
            samples = payload.pop(KEY_MAX_SAMPLES, None)
            shots = payload.pop(KEY_MAX_SHOTS, None)

        command = computer.get_command(command_str)
        computation = Computation(command, payload.pop(KEY_EXPERIMENT, Experiment()))

        if samples is not None:
            PayloadUpdater._safe_add_param(computation, "max_samples", samples)
        if shots is not None:
            PayloadUpdater._safe_add_param(computation, "max_shots", shots)

        base_computation = computation

        if KEY_ITERATOR in payload:
            iterator = payload.pop(KEY_ITERATOR)

            computation = ComputationIterator(computation)
            for iteration in iterator:
                if KEY_NOISE in iteration:
                    del iteration[KEY_NOISE]  # No longer supported - Just ignore it  # TODO: logging.warning ?

                computation.add_iteration(**iteration)

        noise = computation.experiment.noise  # Use legacy way to fill in the noise
        parameters = payload.pop(KEY_PARAMETERS, None)

        for key, value in payload.items():
            PayloadUpdater._safe_add_param(base_computation, key, value)

        return PayloadGenerator.from_computation(computation, noise=noise, parameters=parameters)

    @staticmethod
    def _safe_add_param(computation: Computation, param: str, value: Any) -> None:
        try:
            computation.add_params(**{param: value})
        except TypeError:
            pass  # Logging ?
